language: csharp
solution: UnknownProject.sln
before_install:
  - '[ "$TRAVIS_SECURE_ENV_VARS" == "false" ] || openssl aes-256-cbc -K $encrypted_65728abd4a8d_key -iv $encrypted_65728abd4a8d_iv -in travis-ci/.dropbox_uploader.enc -out ~/.dropbox_uploader -d'
  - wget https://raw.github.com/andreafabrizi/Dropbox-Uploader/master/dropbox_uploader.sh
  - chmod +x dropbox_uploader.sh
  - wget http://www.monogame.net/releases/v3.4/MonoGame.Linux.zip
  - unzip MonoGame.Linux.zip
  - find * -type f -exec chmod 777 {} \;
install:
  - sudo apt-get install -qq monodevelop libopenal-dev referenceassemblies-pcl ttf-mscorefonts-installer gtk-sharp2
  - sudo ./generate.sh && yes Y|sudo ./monogame-linux.run
  - nuget restore UnknownProject.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release UnknownProject.sln
  # Build the content files with the mgcb tool (xbuild doesn't care about that)
  - (cd UnknownProject/Content && mono /opt/monogame-pipeline/MGCB.exe /rebuild /@:"Content.mgcb" /outputDir:"../bin/Release/Content") 
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./UnknownProject.Tests/bin/Release/UnknownProject.Tests.dll
after_script:
  - (cd UnknownProject/bin/Release && zip -r "../../../build_$TRAVIS_JOB_NUMBER.zip" *)
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ -f ~/.dropbox_uploader ] && ./dropbox_uploader.sh upload "build_$TRAVIS_JOB_NUMBER.zip" artifacts/'
branches:
  only:
    - master